# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  displayName: 'Build debug'
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    configuration: debug
    msbuildArchitecture: 'x64'

- task: VSTest@2
  displayName: 'Run debug tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\TestTranslatorCpp.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: '16.0'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true

- task: VSBuild@1
  displayName: 'Build release'
  inputs:
    solution: '**\*.sln' 
    vsVersion: 'latest'
    configuration: release
    msbuildArchitecture: 'x64'

- task: CmdLine@2
  displayName: 'Generate palindromes'
  inputs:
    script: |
      Release\TranslatorCpp.exe -palindromep:SR 8 > palindromes.csv

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: palindromes_SR'
  inputs:
    PathtoPublish: 'palindromes.csv'
    ArtifactName: 'palindromes_SR'
