schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    - daily-pipeline

jobs:
- job: Generate
  pool:
    vmImage: 'windows-latest'
  timeoutInMinutes: 300
  workspace:
    clean: all

  steps:
  - task: VSBuild@1
    displayName: 'Build Release|x64'
    inputs:
      solution: '**/*.sln'
      configuration: release
      msbuildArchitecture: x64
      platform: x64

  - task: CmdLine@2
    displayName: 'Generate palindromes'
    timeoutInMinutes: 200
    inputs:
      script: |
        bin\x64\Release\TranslatorCpp.exe -palindromep:SR 10 0.5 > palindromes_SR_$(Build.BuildId).csv

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: palindromes_SR_daily'
    inputs:
      PathtoPublish: 'palindromes_SR_$(Build.BuildId).csv'
      ArtifactName: 'palindromes_SR_daily'
